service: aws-lambda-http-api-node-authorizer

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
          authorizer:
            name: customAuthorizer

  authorizerFunc:
    handler: authorizer.handler
